---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kurrent
    app.kubernetes.io/instance: kurrent
    app.kubernetes.io/name: kurrent
  name: kurrent
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: kurrent
      app.kubernetes.io/name: kurrent
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: kurrent
        app.kubernetes.io/name: kurrent
    spec:
      containers:
        - name: kurrent
          image: tommybeaton/kurrent:latest-k8s
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: 80
          livenessProbe:
            httpGet:
              path: /status
              port: 80
          volumeMounts:
            - name: appsettings-volume
              mountPath: /app/config
          env:
            - name: ReloadConfigOnChange
              value: "true"
      volumes:
        - name: appsettings-volume
          configMap:
            name: kurrent-config
