apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kurrent
    app.kubernetes.io/instance: kurrent
    app.kubernetes.io/name: kurrent
  name: kurrent
spec:
  replicas: 1
  selector:
    matchLabels: 
      app.kubernetes.io/instance: kurrent
      app.kubernetes.io/name: kurrent
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: kurrent
        app.kubernetes.io/name: kurrent
    spec:
      containers:
        - name: kurrent
          image: tommybeaton/kurrent:latest-k8s # kurrent update; regex: .*dev*.;
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: 80
          livenessProbe:
            httpGet:
              path: /status
              port: 80
          volumeMounts:
            - name: appsettings-volume
              mountPath: /app/appsettings.k8s.json
              subPath: appsettings.k8s.json
      volumes:
        - name: appsettings-volume
          configMap:
            name: kurrent-config
