apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
buildMetadata:
  - managedByLabel
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: lighthouse
  - pairs:
      app.kubernetes.io/version: latest
resources:
  - ./service.yaml
  - ./deployment.yaml
generatorOptions:
  disableNameSuffixHash: true