apiVersion: v1
kind: Service
metadata:
  name: lighthouse-service
spec:
  selector:
    app: lighthouse
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
