apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
buildMetadata:
  - managedByLabel
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: lighthouse
  - pairs:
      app.kubernetes.io/version: latest
resources:
  - https://github.com/TommyBeaton/Lighthouse/kustomize/base
generatorOptions:
  disableNameSuffixHash: true
vars:
  - name: GithubToken
    objref:
      kind: Secret
      name: lighthouse-secrets
      apiVersion: v1
    fieldref:
      fieldpath: data.GITHUB_TOKEN