apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
buildMetadata:
  - managedByLabel
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: kurrent
  - pairs:
      app.kubernetes.io/version: latest
resources:
  - https://github.com/tommybeaton/kurrent/releases/latest/download/release-kurrent.yaml
  - config.yaml
  - secret.yaml
  - ingress.yaml
generatorOptions:
  disableNameSuffixHash: true
vars:
  - name: GithubToken
    objref:
      kind: Secret
      name: kurrent-secrets
      apiVersion: v1
    fieldref:
      fieldpath: data.GITHUB_TOKEN
  - name: SlackToken
    objref:
      kind: Secret
      name: kurrent-secrets
      apiVersion: v1
    fieldref:
      fieldpath: data.SLACK_TOKEN

# If you want to use automatic config reloading, comment out/remove the following lines.
patchesStrategicMerge:
  - reload-config-on-change-patch.yaml
