apiVersion: v1
kind: Secret
metadata:
  name: lighthouse-secrets
type: Opaque
data:
  GITHUB_TOKEN: <Base64-Encoded-Password>

# Note: Use a secret manager such as SOPS or the K8s CLI to create the secret. Don't leave them in plain text.
# Example:
#  kubectl create secret generic lighthouse-secrets \
#  --from-literal=GITHUB_TOKEN=YOUR_PASSWORD 

