name: Release Development Workflow

on:
  pull_request:
    branches:
      - development
    types: [closed]

jobs:
  call-run-unit-tests:
    uses: ./.github/workflows/run-unit-tests.yml
  
  call-build-and-push:
    uses: ./.github/workflows/build-and-push-image.yml
    with:
      version: preview-${{ github.run_number }}
  
  call-publish-kustomization:
    uses: ./.github/workflows/release-kustomization.yaml
    with:
      version: preview-${{ github.run_number }}
