name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  call-build-and-push:
    uses: ./.github/workflows/build-and-push-image.yml
    with:
      version: ${{ github.run_number }}
      environment: latest
      docker_username: ${{ secrets.DOCKERHUB_USERNAME }}
      docker_password: ${{ secrets.DOCKERHUB_PASSWORD }}

  call-publish-kustomization:
    uses: ./.github/workflows/release-kustomization.yaml
    with:
      image: latest-k8s-${{ github.run_number }}